---
service: duckee-api
frameworkVersion: '3'
provider:
  name: aws
  runtime: nodejs16.x
  region: ap-northeast-2
  timeout: 900
  environment: ${file(./serverless-load-secrets.js)}
  iamRoleStatements:
    # Allow functions to list all buckets
    - Effect: Allow
      Action: 's3:ListBucket'
      Resource: '*'
    # Allow functions to read/write objects in a bucket
    - Effect: Allow
      Action:
        - 's3:GetObject'
        - 's3:PutObject'
      Resource:
        - 'arn:aws:s3:::static.duckee.xyz/*'
    - Effect: Allow
      Action:
        - 'lambda:InvokeFunction'
      Resource:
        - 'arn:aws:lambda:ap-northeast-2:600288883458:function:duckee-api-dev-asyncTask'
functions:
  app:
    handler: src/serverless.handler
    timeout: 30
    events:
      - http: 'ANY /'
      - http: 'ANY /{proxy+}'
  asyncTask:
    handler: src/serverless.asyncTaskHandler
    timeout: 900

plugins:
  - serverless-esbuild
  - serverless-offline
  - serverless-domain-manager
#  - serverless-plugin-warmup

custom:
  esbuild:
    sourcemap: inline
    plugins: ./serverless-esbuild-plugins.js
  stages:
    dev:
      domain: api.duckee.xyz
      cerficiateArn: arn:aws:acm:us-east-1:600288883458:certificate/afe87ee5-fbf8-424e-8ead-65b8850da2a2
      stageEnviron: development

  serverless-offline:
    noPrependStageInUrl: true

  customDomain:
    domainName: ${self:custom.stages.${opt:stage, 'dev'}.domain}
    certificateArn: ${self:custom.stages.${opt:stage, 'dev'}.cerficiateArn}
    createRoute53Record: true
